--------------------------------------------------------------------------------
-- Comercial La Estrella - Script de creacion de base de datos (DDL)
-- Motor: Oracle Database (probado sobre Oracle XE 21c, gvenzl/oracle-xe:21-slim)
--
-- Orden de ejecucion: este script se ejecuta de arriba hacia abajo, de una sola
-- pasada, contra un esquema vacio. El orden respeta las dependencias de llave
-- foranea (cada tabla solo referencia tablas ya creadas antes que ella).
--
-- Convencion de nombres: snake_case en minusculas, unico estilo en todo el
-- script (tablas, columnas y restricciones).
--
-- Llaves primarias: se usan columnas NUMBER con IDENTITY (GENERATED BY DEFAULT
-- ON NULL). Esto permite que la carga de datos de prueba inserte los IDs
-- explicitos tal como vienen en el Excel (para conservar las referencias entre
-- hojas), y que cualquier insercion futura sin ID explicito se autogenere.
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 1. UBICACION GEOGRAFICA
--------------------------------------------------------------------------------

CREATE TABLE pais (
    id_pais       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_pais   VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_pais PRIMARY KEY (id_pais),
    CONSTRAINT uq_pais_nombre UNIQUE (nombre_pais)
);

CREATE TABLE departamento (
    id_departamento     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_departamento VARCHAR2(50) NOT NULL,
    id_pais             NUMBER NOT NULL,
    CONSTRAINT pk_departamento PRIMARY KEY (id_departamento),
    CONSTRAINT fk_departamento_pais FOREIGN KEY (id_pais) REFERENCES pais (id_pais),
    -- el nombre de un departamento no se repite dentro del mismo pais
    CONSTRAINT uq_departamento_nombre_pais UNIQUE (nombre_departamento, id_pais)
);

CREATE TABLE municipio (
    id_municipio      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_municipio  VARCHAR2(60) NOT NULL,
    id_departamento   NUMBER NOT NULL,
    CONSTRAINT pk_municipio PRIMARY KEY (id_municipio),
    CONSTRAINT fk_municipio_departamento FOREIGN KEY (id_departamento) REFERENCES departamento (id_departamento),
    -- el nombre de un municipio no se repite dentro del mismo departamento
    CONSTRAINT uq_municipio_nombre_depto UNIQUE (nombre_municipio, id_departamento)
);


--------------------------------------------------------------------------------
-- 2. CATALOGOS GENERALES
--------------------------------------------------------------------------------

CREATE TABLE tipo_tienda (
    id_tipo_tienda      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_tipo_tienda  VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_tipo_tienda PRIMARY KEY (id_tipo_tienda),
    CONSTRAINT uq_tipo_tienda_nombre UNIQUE (nombre_tipo_tienda)
);

CREATE TABLE tipo_identificacion (
    id_tipo_identificacion      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_tipo_identificacion  VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_tipo_identificacion PRIMARY KEY (id_tipo_identificacion),
    CONSTRAINT uq_tipo_identificacion_nombre UNIQUE (nombre_tipo_identificacion)
);

CREATE TABLE cargo (
    id_cargo      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_cargo  VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_cargo PRIMARY KEY (id_cargo),
    CONSTRAINT uq_cargo_nombre UNIQUE (nombre_cargo)
);

CREATE TABLE categoria (
    id_categoria      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_categoria  VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre_categoria)
);

CREATE TABLE marca (
    id_marca      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_marca  VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_marca PRIMARY KEY (id_marca),
    CONSTRAINT uq_marca_nombre UNIQUE (nombre_marca)
);

CREATE TABLE estado_venta (
    id_estado_venta      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_estado_venta  VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_estado_venta PRIMARY KEY (id_estado_venta),
    CONSTRAINT uq_estado_venta_nombre UNIQUE (nombre_estado_venta),
    CONSTRAINT ck_estado_venta_valores CHECK (nombre_estado_venta IN ('REGISTRADA', 'PAGADA', 'ANULADA'))
);

CREATE TABLE metodo_pago (
    id_metodo_pago      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_metodo_pago  VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_metodo_pago PRIMARY KEY (id_metodo_pago),
    CONSTRAINT uq_metodo_pago_nombre UNIQUE (nombre_metodo_pago)
);


--------------------------------------------------------------------------------
-- 3. TIENDAS Y PERSONAS
--------------------------------------------------------------------------------

CREATE TABLE tienda (
    id_tienda         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_tienda     VARCHAR2(100) NOT NULL,
    direccion_tienda  VARCHAR2(150) NOT NULL,
    telefono_tienda   VARCHAR2(20) NOT NULL,
    id_municipio      NUMBER NOT NULL,
    id_tipo_tienda    NUMBER NOT NULL,
    CONSTRAINT pk_tienda PRIMARY KEY (id_tienda),
    CONSTRAINT fk_tienda_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id_municipio),
    CONSTRAINT fk_tienda_tipo_tienda FOREIGN KEY (id_tipo_tienda) REFERENCES tipo_tienda (id_tipo_tienda)
);

-- Supertipo: atributos comunes a empleado y cliente (especializacion disjunta
-- y total; cada fila de persona pertenece exactamente a una de las dos tablas
-- subtipo, nunca a ambas).
CREATE TABLE persona (
    id_persona    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombres       VARCHAR2(50) NOT NULL,
    apellidos     VARCHAR2(50) NOT NULL,
    telefono      VARCHAR2(20) NOT NULL,
    correo        VARCHAR2(100),
    direccion     VARCHAR2(150) NOT NULL,
    id_municipio  NUMBER NOT NULL,
    CONSTRAINT pk_persona PRIMARY KEY (id_persona),
    CONSTRAINT fk_persona_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id_municipio),
    -- nulable a nivel de tabla porque persona es compartida por empleado y
    -- cliente; Oracle permite multiples NULL en una columna UNIQUE, asi que
    -- esto ya satisface "correo unico cuando se encuentre registrado".
    -- La regla "el correo es obligatorio para empleados" NO puede expresarse
    -- de forma declarativa aqui (depende de en cual subtipo cae la persona):
    -- se debe verificar con una consulta de validacion.
    CONSTRAINT uq_persona_correo UNIQUE (correo)
);

CREATE TABLE empleado (
    id_empleado          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_persona           NUMBER NOT NULL,
    fecha_contratacion   DATE NOT NULL,
    id_tienda            NUMBER NOT NULL,
    id_cargo             NUMBER NOT NULL,
    CONSTRAINT pk_empleado PRIMARY KEY (id_empleado),
    CONSTRAINT fk_empleado_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona),
    -- relacion 1:1 con persona (subtipo)
    CONSTRAINT uq_empleado_persona UNIQUE (id_persona),
    CONSTRAINT fk_empleado_tienda FOREIGN KEY (id_tienda) REFERENCES tienda (id_tienda),
    CONSTRAINT fk_empleado_cargo FOREIGN KEY (id_cargo) REFERENCES cargo (id_cargo)
    -- regla "la fecha de contratacion no puede ser posterior a hoy": Oracle no
    -- permite SYSDATE dentro de un CHECK (debe ser deterministico), y un
    -- trigger esta fuera del alcance del proyecto. Se documenta como regla no
    -- declarativa y se verifica con consulta de validacion:
    --   SELECT * FROM empleado WHERE fecha_contratacion > SYSDATE; -- 0 filas
);

CREATE TABLE cliente (
    id_cliente               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_persona               NUMBER NOT NULL,
    id_tipo_identificacion   NUMBER NOT NULL,
    numero_identificacion    VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT fk_cliente_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona),
    -- relacion 1:1 con persona (subtipo)
    CONSTRAINT uq_cliente_persona UNIQUE (id_persona),
    CONSTRAINT fk_cliente_tipo_ident FOREIGN KEY (id_tipo_identificacion) REFERENCES tipo_identificacion (id_tipo_identificacion),
    -- la combinacion tipo + numero de identificacion debe ser unica
    CONSTRAINT uq_cliente_tipo_numero UNIQUE (id_tipo_identificacion, numero_identificacion)
);


--------------------------------------------------------------------------------
-- 4. PRODUCTOS
--------------------------------------------------------------------------------

CREATE TABLE producto (
    id_producto           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre_producto       VARCHAR2(100) NOT NULL,
    descripcion_producto  VARCHAR2(300),
    id_categoria          NUMBER NOT NULL,
    id_marca              NUMBER NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (id_producto),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria),
    CONSTRAINT fk_producto_marca FOREIGN KEY (id_marca) REFERENCES marca (id_marca)
);

-- Entidad asociativa: precio vigente y existencia dependen de la combinacion
-- (tienda, producto), no solo del producto. No todo producto esta disponible
-- en todas las tiendas.
CREATE TABLE catalogo_tienda_producto (
    id_tienda          NUMBER NOT NULL,
    id_producto        NUMBER NOT NULL,
    precio_vigente     NUMBER(10,2) NOT NULL,
    existencia_actual  NUMBER NOT NULL,
    CONSTRAINT pk_catalogo_tienda_producto PRIMARY KEY (id_tienda, id_producto),
    CONSTRAINT fk_catprod_tienda FOREIGN KEY (id_tienda) REFERENCES tienda (id_tienda),
    CONSTRAINT fk_catprod_producto FOREIGN KEY (id_producto) REFERENCES producto (id_producto),
    CONSTRAINT ck_catprod_precio CHECK (precio_vigente > 0),
    CONSTRAINT ck_catprod_existencia CHECK (existencia_actual >= 0)
);


--------------------------------------------------------------------------------
-- 5. VENTAS Y PAGOS
--------------------------------------------------------------------------------

CREATE TABLE venta (
    id_venta          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    fecha_venta       DATE NOT NULL,
    id_tienda         NUMBER NOT NULL,
    id_empleado       NUMBER NOT NULL,
    id_cliente        NUMBER NOT NULL,
    id_estado_venta   NUMBER NOT NULL,
    CONSTRAINT pk_venta PRIMARY KEY (id_venta),
    CONSTRAINT fk_venta_tienda FOREIGN KEY (id_tienda) REFERENCES tienda (id_tienda),
    CONSTRAINT fk_venta_empleado FOREIGN KEY (id_empleado) REFERENCES empleado (id_empleado),
    CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT fk_venta_estado FOREIGN KEY (id_estado_venta) REFERENCES estado_venta (id_estado_venta)
    -- regla "el empleado debe pertenecer a la misma tienda de la venta":
    -- depende de dos tablas, no expresable como CHECK/FK declarativo.
    -- Verificar con consulta de validacion.
);

CREATE TABLE detalle_venta (
    id_venta         NUMBER NOT NULL,
    id_producto      NUMBER NOT NULL,
    cantidad         NUMBER NOT NULL,
    precio_unitario  NUMBER(10,2) NOT NULL,
    subtotal         NUMBER(10,2) NOT NULL,
    -- clave primaria compuesta: satisface "un producto no puede registrarse
    -- mas de una vez en la misma venta" de forma puramente declarativa
    CONSTRAINT pk_detalle_venta PRIMARY KEY (id_venta, id_producto),
    CONSTRAINT fk_detventa_venta FOREIGN KEY (id_venta) REFERENCES venta (id_venta),
    CONSTRAINT fk_detventa_producto FOREIGN KEY (id_producto) REFERENCES producto (id_producto),
    CONSTRAINT ck_detventa_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detventa_precio CHECK (precio_unitario > 0),
    -- el subtotal se deriva de cantidad * precio_unitario; se valida de forma
    -- declarativa, sin necesidad de trigger
    CONSTRAINT ck_detventa_subtotal CHECK (subtotal = cantidad * precio_unitario)
);

CREATE TABLE pago (
    id_pago         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_venta        NUMBER NOT NULL,
    id_metodo_pago  NUMBER NOT NULL,
    monto_pagado    NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_pago PRIMARY KEY (id_pago),
    CONSTRAINT fk_pago_venta FOREIGN KEY (id_venta) REFERENCES venta (id_venta),
    CONSTRAINT fk_pago_metodo FOREIGN KEY (id_metodo_pago) REFERENCES metodo_pago (id_metodo_pago),
    CONSTRAINT ck_pago_monto CHECK (monto_pagado > 0)
    -- regla "la suma de pagos de una venta PAGADA debe igualar el total de
    -- sus detalles": depende de dos tablas, no expresable como CHECK
    -- declarativo. Verificar con consulta de validacion (ver consulta 8,
    -- "ventas pendientes de pago").
);

--------------------------------------------------------------------------------
-- Fin del script. 19 tablas creadas, listas para carga de datos.
--------------------------------------------------------------------------------
